# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
