# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chat_history',
            field=models.TextField(default=''),
        ),
    ]
