# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='chat_history',
            field=models.TextField(default='{"chat_history":[]}'),
        ),
    ]
