# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('room', '0004_auto_20171230_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
