# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
