# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profile_tree'),
        ('room', '0006_auto_20180101_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='particpant',
            field=models.ManyToManyField(related_name='room_participant_set', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_owner_set', to='student.Student'),
        ),
    ]
