# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180101_2352'),
        ('room', '0007_auto_20180101_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ManyToManyField(related_name='room_author_set', to='student.Student'),
        ),
    ]
