# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='require_help',
            field=models.BooleanField(default=False),
        ),
    ]
