# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_exercise_problem_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='question',
            new_name='material',
        ),
    ]
