# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20171230_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='problem_tree',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='test_case',
            field=models.TextField(blank=True, default=''),
        ),
    ]
