# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180101_2352'),
        ('exercise', '0005_auto_20171230_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='complete_student',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
