# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_exercise_complete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='problem_tree',
        ),
        migrations.AddField(
            model_name='exercise',
            name='character_skill',
            field=models.TextField(blank=True, default=''),
        ),
    ]
