# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20180322_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='common_skill',
            field=models.TextField(blank=True, default=''),
        ),
    ]
