# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_exercise_common_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='complete_student',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
