# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20180402_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='character_skill',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='common_skill',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
