# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20180402_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='character_skill',
        ),
    ]
