# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_cluster_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='skills',
            new_name='necessary_skill',
        ),
        migrations.AddField(
            model_name='cluster',
            name='redundant_skill',
            field=models.TextField(default=''),
        ),
    ]
