# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20180321_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='centroid',
            new_name='center',
        ),
    ]
