# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_auto_20180321_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='character_skill',
            field=models.TextField(default=''),
        ),
    ]
