# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_cluster_character_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='other_skill',
            field=models.TextField(default=''),
        ),
    ]
