# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171108_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reply_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
