# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
