# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20180101_1925'),
        ('version', '0002_auto_20180101_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='version',
            name='student',
        ),
        migrations.AddField(
            model_name='version',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
            preserve_default=False,
        ),
    ]
