# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20180101_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='status',
        ),
        migrations.AddField(
            model_name='version',
            name='overall_success',
            field=models.BooleanField(default=False),
        ),
    ]
