# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0004_auto_20180104_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='passed_test_case',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='total_test_case',
            field=models.IntegerField(default=0),
        ),
    ]
