# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_exercise_complete_student'),
        ('version', '0006_auto_20180320_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
