# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0009_auto_20180325_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='cluster',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cluster.Cluster'),
        ),
    ]
